### ISSUE TITLE
Tried to run command without establishing a connection

### ISSUE THREAD

**Issue by fatih-yavuz** [Codeception/CodeceptJS#1939]
#### What are you trying to achieve?
We have 70 tests are being executed in parallel using puppeteer and chrome without any problem.
I'm trying to do the same by using, Webdriver helper, dockerized selenium and firefox.

#### What do you get instead?
When I run tests sequentially, there is no problem however when I run tests in parallel, 2 or 3 tests fail with following reason.
`Tried to run command without establishing a connection`
`[2] Error | invalid session id: No active session with ID ....`

When I distribute tests over 10 chunks as I do on puppeteer, I even get 
`trying to get isW3C of undefined` on **some** chunks not all. This seems pretty weird.
This error occurs when wrong browser name is passed rather than chrome or firefox on the config file.

Anyone can help with this? Thanks

### Details

docker-compose.yml
```
version: '3'
services:
  codeceptjs-webdriver:
    container_name: "codeceptjs-webdriver"
    depends_on:
      - selenium
    volumes:
      - .:/tests
    build:
      context: .
      dockerfile: Dockerfile-webdriver
    links:
      - selenium
  selenium:
    image:
      vvoyer/selenium-standalone
    logging:
      driver: none

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
```

Dockerfile
```
FROM codeception/codeceptjs
...
```

* Configuration file:

```js
module.exports = {
    tests: './tests/**/*-test.js',
    grep: process.env.testTag || null,
    output: process.env.outputFolder || './output',
    mocha: {
        retries: process.env.retries || 0
    },
    include: {
        I: './steps-file.js'
    },
    name: 'e2e',
    multiple: {
        parallel: {
            chunks: 2,
            browsers: ['firefox']
        }
    },
    helpers: {
      WebDriver: {
            url: process.env.testUrl
            browser: 'firefox',
            host: process.env.seleniumHost || '127.0.0.1',
            port: 4444,
            desiredCapabilities: {
                acceptInsecureCerts: true,
                firefoxOptions: {
                    args: ['-safe-mode']
                }
            },
            windowSize: '1920x1080',
            waitForTimeout: 20000,
            waitForAction: 1000,
            getPageTimeout: 60000
        },
        REST: {
            endpoint: `${testUrl}`,
            defaultHeaders: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        },
        ApiDataFactory: {
            endpoint: `${testUrl}`,
            cleanup: false,
            headers: {
                'Content-Type': 'application/json',
                Accept: 'application/json'
            },
            factories: {
                user: {
                    uri: '/e2e/environment-setup/instructor',
                    factory: './factories/user'
                },
            }
        }
    },
    hooks: [
        'hooks/on-test-fail.js',
        'hooks/on-unhandled-rejection.js',
        'hooks/on-test-start.js',
        'hooks/on-test-finish.js'
    ],
    plugins: {
        wdio: {
            enabled: true,
            services: ['selenium-standalone']
        }
    }
};
```
