### ISSUE TITLE
invalid reporter "mochawesome" for Nightmare tests run via docker-compose

### ISSUE THREAD

**Issue by mallorym** [Codeception/CodeceptJS#865]
First of all, love the project. 😄 I've been playing around with running CodeceptJS + Nightmare tests via docker-compose and ran into a problem with trying out the mochawesome reporter. I get an error when running with `docker-compose run`. 

Looks like the Docker image is missing the **mochawesome** package. I was able to fix things for my purposes, but it's a little hacky. Appreciate the help.

#### error I get
```javascript
"mochawesome" reporter not found

invalid reporter "mochawesome"

Error:
    at Mocha.reporter (/codecept/node_modules/mocha/lib/mocha.js:174:13)
    at new Mocha (/codecept/node_modules/mocha/lib/mocha.js:90:8)
    at Function.create (/codecept/lib/mocha_factory.js:12:13)
    at Function.create (/codecept/lib/container.js:26:36)
    at Codecept.init (/codecept/lib/codecept.js:47:15)
    at Command.module.exports (/codecept/lib/command/run.js:35:14)
    at Command.listener (/codecept/node_modules/commander/index.js:315:8)

    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/codecept/node_modules/commander/index.js:653:12)
```
### Details
* package.json:
```json
"devDependencies": {
    "codeceptjs": "^1.0.2",
    "codeceptjs-nightmare": "^1.1.0",
    "mochawesome": "^3.0.1",
    "nightmare": "^2.10.0",
    "nightmare-upload": "^0.1.1"
  }
```
* docker-compose:
```yaml
version: '3'
services:
  codeceptjs:
    image: codeception/codeceptjs
    environment:
      - CODECEPT_ARGS=--reporter mochawesome
    volumes:
      - .:/tests
    command: bash -c "cd .. && cd /tests && npm install && bash ../codecept/docker/run.sh"
    container_name: docker-nightmare
```
